project_id = "nccyrvfnvjngfyfvgnww"

[functions.create-mercadopago-payment]
verify_jwt = true

[functions.calculate-shipping]
verify_jwt = true

[functions.process-transparent-payment]
verify_jwt = true

[functions.mercadopago-webhook]
verify_jwt = false