project_id = "nccyrvfnvjngfyfvgnww"

[functions.create-mercadopago-payment]
verify_jwt = true

[functions.calculate-shipping]
verify_jwt = true

[functions.process-transparent-payment]
verify_jwt = true

[functions.mercadopago-webhook]
verify_jwt = false

[functions.send-order-email]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = true

[functions.create-client]
verify_jwt = true

[functions.create-ebd-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.generate-recurring-bills]
verify_jwt = true

[functions.bling-callback]
verify_jwt = false

[functions.bling-refresh-token]
verify_jwt = true

[functions.bling-sync-products]
verify_jwt = true

[functions.bling-check-stock]
verify_jwt = true

[functions.bling-create-order]
verify_jwt = true

[functions.bling-update-order]
verify_jwt = true

[functions.ebd-create-lead-accounts]
verify_jwt = true

[functions.update-user-password]
verify_jwt = true
